# Generated by Django 5.1.6 on 2025-03-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_delete_user_remove_receipt_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt'),
        ),
    ]
